Update cml.yaml

diff --git a/.github/workflows/cml.yaml b/.github/workflows/cml.yaml
--- a/.github/workflows/cml.yaml
+++ b/.github/workflows/cml.yaml
@@ -32,21 +32,16 @@ jobs:
       - name: Upgrade pip
         run: python -m pip install --upgrade pip
 
+      - name: Verify Tcl/Tk Installation
+        run: |
+          python -m tkinter || echo "Tcl/Tk is not required for headless execution."
+        shell: cmd
+
       - name: Install dependencies
         run: |
           python -m pip install -r requirements.txt
         env:
           PYTHONIOENCODING: utf-8
-
-      - name: Verify Tcl/Tk Installation
-        run: |
-          try {
-            python -m tkinter
-            Write-Host "Tcl/Tk is installed and working."
-          } catch {
-            Write-Host "Tcl/Tk is not required for headless execution."
-          }
-        shell: pwsh
 
       - name: Train LSTM Model
         run: |
